import { css, cx } from '../../styled-system/css'

/**
 * The material library. Generated by the orchestrator from
 * scripts/templates/Material.tsx.template on every run, exactly the way
 * app/components/BrandLockup.tsx is. Do not edit by hand and do not draw a
 * material anywhere else: scripts/utils/build-validator.js fails the build
 * over an `feTurbulence` in any file the engineer owns, the way it fails a
 * pasted brand mark.
 *
 * Why it exists: every nightly build was a flat field, type and a hairline,
 * because nothing in the pipeline could put texture on a page. External
 * images are banned and nothing generates a picture, so the texture is
 * synthesized here, from the semantic tokens and the day's seed, and the Art
 * Director declares which one in ===SHELL=== as `ground_material`. See #505.
 *
 * PLACEMENT. `<Ground>` is absolute, inset 0, pointer-events none, z-index 0.
 * It is meant to be the first child of a relatively positioned hero, with the
 * hero's content in a sibling set position: relative and z-index: 1 so it
 * paints above the material. The material sits ON a token ground and never
 * replaces it: the colour floor is measured off backgrounds, and a texture
 * layer paints none of its own.
 *
 * DETERMINISM. Everything follows from `seed`: no Math.random, no Date. Panda
 * resolves styles at extract time, so seed-derived values cannot be written
 * into css() at runtime. Each material instead carries a small table of
 * static variants (pitch, rotation, blob placement) and the seed picks a row;
 * the one value that is genuinely continuous, grain's baseFrequency, is an
 * SVG filter attribute, which Panda cannot express and which is set directly.
 */

type GroundMaterial = 'none' | 'grain' | 'mesh' | 'halftone' | 'rule' | 'dots'

type GroundProps = {
  material: GroundMaterial
  /** The day's seed, from scripts/utils/material.js materialSeed(date). */
  seed: number
  className?: string
}

/**
 * Pick a row of a variant table from the seed. `salt` separates the picks a
 * single material makes (pitch and rotation, say) so they do not move in
 * lockstep. A short integer mix, not a hash: the seed is already an FNV-1a
 * result and only has to be spread across a handful of rows.
 */
function pick<T>(table: readonly T[], seed: number, salt: number): T {
  let h = (seed ^ Math.imul(salt + 1, 0x9e3779b1)) >>> 0
  h = Math.imul(h ^ (h >>> 16), 0x85ebca6b) >>> 0
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35) >>> 0
  h = (h ^ (h >>> 16)) >>> 0
  return table[h % table.length]
}

const root = css({
  position: 'absolute',
  inset: '0px',
  zIndex: 0,
  pointerEvents: 'none',
  overflow: 'hidden',
})

const layer = css({
  position: 'absolute',
  inset: '0px',
})

/**
 * grain: fractal noise, mapped to alpha, flooded with the `text` ink and
 * laid over the field at low opacity. The svg is set in `text` so the
 * flood's currentColor follows the day's ink on any ground.
 */
const grainSvg = css({
  position: 'absolute',
  inset: '0px',
  width: '100%',
  height: '100%',
  display: 'block',
  color: 'text',
  opacity: 0.2,
})

function Grain({ seed }: { seed: number }) {
  // 0.6000 to 0.9000, four places, from the seed.
  const baseFrequency = (0.6 + (seed % 3001) / 10000).toFixed(4)
  const id = `ground-grain-${seed}`
  return (
    <svg
      className={grainSvg}
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
      preserveAspectRatio="none"
    >
      <filter id={id} x="0" y="0" width="100%" height="100%" colorInterpolationFilters="sRGB">
        <feTurbulence
          type="fractalNoise"
          baseFrequency={baseFrequency}
          numOctaves="3"
          seed={seed % 1000}
          stitchTiles="stitch"
        />
        <feColorMatrix type="luminanceToAlpha" result="alpha" />
        <feFlood floodColor="currentColor" result="ink" />
        <feComposite in="ink" in2="alpha" operator="in" />
      </filter>
      <rect width="100%" height="100%" filter={`url(#${id})`} />
    </svg>
  )
}

/**
 * mesh: three or four radial blooms in `accent`, `accentAlt` and `bg` at
 * seed-picked positions and radii, layered with background-image.
 */
const meshVariants = [
  css({
    backgroundImage:
      'radial-gradient(at 18% 14%, {colors.accent} 0px, transparent 46%), radial-gradient(at 82% 22%, {colors.accentAlt} 0px, transparent 40%), radial-gradient(at 28% 86%, {colors.bg} 0px, transparent 52%), radial-gradient(at 76% 78%, {colors.accent} 0px, transparent 34%)',
  }),
  css({
    backgroundImage:
      'radial-gradient(at 70% 10%, {colors.accent} 0px, transparent 50%), radial-gradient(at 12% 40%, {colors.accentAlt} 0px, transparent 38%), radial-gradient(at 60% 90%, {colors.bg} 0px, transparent 44%)',
  }),
  css({
    backgroundImage:
      'radial-gradient(at 40% 30%, {colors.accentAlt} 0px, transparent 42%), radial-gradient(at 90% 70%, {colors.accent} 0px, transparent 48%), radial-gradient(at 8% 88%, {colors.accent} 0px, transparent 36%), radial-gradient(at 55% 60%, {colors.bg} 0px, transparent 56%)',
  }),
  css({
    backgroundImage:
      'radial-gradient(at 10% 10%, {colors.accentAlt} 0px, transparent 54%), radial-gradient(at 92% 12%, {colors.accent} 0px, transparent 32%), radial-gradient(at 50% 100%, {colors.accent} 0px, transparent 46%), radial-gradient(at 30% 55%, {colors.bg} 0px, transparent 40%)',
  }),
  css({
    backgroundImage:
      'radial-gradient(at 85% 85%, {colors.accent} 0px, transparent 58%), radial-gradient(at 20% 70%, {colors.accentAlt} 0px, transparent 44%), radial-gradient(at 65% 15%, {colors.bg} 0px, transparent 38%)',
  }),
  css({
    backgroundImage:
      'radial-gradient(at 50% 0%, {colors.accentAlt} 0px, transparent 48%), radial-gradient(at 0% 100%, {colors.accent} 0px, transparent 42%), radial-gradient(at 100% 55%, {colors.accent} 0px, transparent 36%), radial-gradient(at 45% 80%, {colors.bg} 0px, transparent 50%)',
  }),
] as const

/**
 * halftone: a dot screen in `text` at low alpha. Dot size and pitch come
 * from one pick, the rotation from another; the layer is three times the
 * hero in each direction so a 15 degree turn leaves no bare corner on a
 * hero up to seven times as wide as it is tall.
 */
const halftoneLayer = css({
  position: 'absolute',
  inset: '-100%',
  color: 'text',
  opacity: 0.14,
  backgroundRepeat: 'repeat',
})

const halftonePitches = [
  css({
    backgroundImage: 'radial-gradient(circle, currentColor 1.1px, transparent 1.3px)',
    backgroundSize: '6px 6px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, currentColor 1.5px, transparent 1.7px)',
    backgroundSize: '8px 8px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, currentColor 1.9px, transparent 2.1px)',
    backgroundSize: '10px 10px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, currentColor 2.4px, transparent 2.6px)',
    backgroundSize: '12px 12px',
  }),
] as const

const halftoneRotations = [
  css({ transform: 'rotate(-15deg)' }),
  css({ transform: 'rotate(-8deg)' }),
  css({ transform: 'rotate(8deg)' }),
  css({ transform: 'rotate(15deg)' }),
] as const

/** rule: ruled lines in `border`, pitch from the seed. */
const rulePitches = [
  css({
    backgroundImage:
      'repeating-linear-gradient(to bottom, {colors.border} 0px, {colors.border} 1px, transparent 1px, transparent 16px)',
  }),
  css({
    backgroundImage:
      'repeating-linear-gradient(to bottom, {colors.border} 0px, {colors.border} 1px, transparent 1px, transparent 24px)',
  }),
  css({
    backgroundImage:
      'repeating-linear-gradient(to bottom, {colors.border} 0px, {colors.border} 1px, transparent 1px, transparent 32px)',
  }),
  css({
    backgroundImage:
      'repeating-linear-gradient(to bottom, {colors.border} 0px, {colors.border} 1px, transparent 1px, transparent 48px)',
  }),
] as const

/** dots: a dot field in `accent`, pitch from the seed. */
const dotsLayer = css({
  position: 'absolute',
  inset: '0px',
  opacity: 0.55,
  backgroundRepeat: 'repeat',
})

const dotsPitches = [
  css({
    backgroundImage: 'radial-gradient(circle, {colors.accent} 1.2px, transparent 1.5px)',
    backgroundSize: '14px 14px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, {colors.accent} 1.5px, transparent 1.8px)',
    backgroundSize: '18px 18px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, {colors.accent} 1.8px, transparent 2.1px)',
    backgroundSize: '24px 24px',
  }),
  css({
    backgroundImage: 'radial-gradient(circle, {colors.accent} 2.2px, transparent 2.5px)',
    backgroundSize: '32px 32px',
  }),
] as const

function Layer({ material, seed }: { material: GroundMaterial; seed: number }) {
  switch (material) {
    case 'grain':
      return <Grain seed={seed} />
    case 'mesh':
      return <div className={cx(layer, pick(meshVariants, seed, 0))} />
    case 'halftone':
      return (
        <div
          className={cx(
            halftoneLayer,
            pick(halftonePitches, seed, 1),
            pick(halftoneRotations, seed, 2)
          )}
        />
      )
    case 'rule':
      return <div className={cx(layer, pick(rulePitches, seed, 3))} />
    case 'dots':
      return <div className={cx(dotsLayer, pick(dotsPitches, seed, 4))} />
    default:
      return null
  }
}

/**
 * The declared material, over the hero's own field.
 *
 * `data-ground-material` is how the surface gate and the DOM tests find the
 * layer; the seed rides beside it so an archived page says which draw it was.
 */
export function Ground({ material, seed, className }: GroundProps) {
  if (material === 'none') return null
  return (
    <div
      className={cx(root, className)}
      data-ground-material={material}
      data-ground-seed={seed}
      aria-hidden="true"
    >
      <Layer material={material} seed={seed} />
    </div>
  )
}
