import { css } from '../../styled-system/css'
import { projects } from '../content/projects'

/**
 * The white paper. Generated by the orchestrator from
 * scripts/templates/WhitePaper.tsx.template on every run, the way
 * app/components/Material.tsx is. Do not edit by hand: edit the template.
 * scripts/utils/build-validator.js fails the build when this file differs
 * from the template, and when app/routes/work.$slug.tsx stops rendering it
 * for the `dougmar-ch` slug.
 *
 * Why it exists: the page at /work/dougmar-ch is the argument the site rests
 * on and the one most likely to be linked from outside, and it was redesigned
 * every night with everything else. On 2026-09-20 the generated version set
 * the constraints as wrapped tags and rewrote "redesigns itself" at render
 * time. The layout is fixed here. See #533.
 *
 * WHAT FOLLOWS THE DAY. Colour and typeface, and nothing else. Every colour is
 * one of the fifteen frozen semantic names (scripts/utils/semantic-contract.js)
 * and every face is `display` or `body`, the two font tokens all chassis
 * define. Weights go through the weight tokens, which each chassis maps onto
 * cuts it loads, so no day gets a synthesized bold.
 *
 * WHAT DOES NOT. Sizes, leading, tracking, spacing and the measure are
 * literal values. The chassis ramp runs from a 1.333 ratio to 1.618 and the
 * spacing scale is derived from the same chassis, so a step name here would
 * hand the hierarchy back to the night. The column is 40rem, about 70
 * characters of an ordinary text face at 1.125rem. Accent is only ever a mark
 * (a rule, an underline), never an ink, because nothing promises it clears
 * 4.5:1 on bg.
 *
 * It takes no props. The words come from app/content/projects.ts, which the
 * write layer refuses to every agent, and a component with no inputs cannot
 * be handed the wrong project. The route keeps the day's shell around it: the
 * lockup, the `h1` carrying the title, the nav and the foot stay the
 * engineer's, under the same rules as every other route.
 *
 * Every css() call is at module scope with literal values. Panda extracts at
 * build time, and a value that only exists at run time yields a class with no
 * rule behind it (2026-09-19, PR #525).
 */

const WHITE_PAPER_SLUG = 'dougmar-ch'

function hostOf(url: string): string {
  try {
    const host = new URL(url).hostname
    return host.startsWith('www.') ? host.slice(4) : host
  } catch {
    return url
  }
}

export function WhitePaper() {
  const paper = projects.find((p) => p.slug === WHITE_PAPER_SLUG)
  if (!paper) return null

  const facts: [string, string | number | undefined][] = [
    ['Role', paper.role],
    ['Year', paper.year],
    ['Timeline', paper.timeline],
    ['Status', paper.status],
    ['Type', paper.type],
  ]

  return (
    <article className={articleClass} data-white-paper="">
      <div className={columnClass}>
        <dl className={factsClass}>
          {facts.map(([label, value]) =>
            value === undefined ? null : (
              <div key={label}>
                <dt className={labelClass}>{label}</dt>
                <dd className={factValueClass}>{value}</dd>
              </div>
            )
          )}
        </dl>
        {paper.context && <p className={ledeClass}>{paper.context}</p>}
      </div>

      {paper.problem && (
        <section className={sectionClass} aria-labelledby="wp-problem">
          <h2 id="wp-problem" className={sideHeadClass}>
            Problem
          </h2>
          <p className={proseClass}>{paper.problem}</p>
        </section>
      )}

      {paper.constraints && paper.constraints.length > 0 && (
        <section className={sectionClass} aria-labelledby="wp-constraints">
          <h2 id="wp-constraints" className={sideHeadClass}>
            Constraints
          </h2>
          <ul className={plainListClass}>
            {paper.constraints.map((constraint) => (
              <li key={constraint} className={constraintClass}>
                <span className={bulletClass} aria-hidden="true" />
                <span>{constraint}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {paper.approach && (
        <section className={sectionClass} aria-labelledby="wp-approach">
          <h2 id="wp-approach" className={sideHeadClass}>
            Approach
          </h2>
          <p className={proseClass}>{paper.approach}</p>
        </section>
      )}

      {paper.process && paper.process.length > 0 && (
        <section className={sectionClass} aria-labelledby="wp-process">
          <h2 id="wp-process" className={sideHeadClass}>
            Process
          </h2>
          <ol className={plainListClass}>
            {paper.process.map((step, i) => (
              <li key={step.phase} className={phaseClass}>
                <span className={phaseNumberClass} aria-hidden="true">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <div>
                  <h3 className={phaseNameClass}>{step.phase}</h3>
                  <p className={phaseDoesClass}>{step.does}</p>
                  <p className={producesClass}>
                    <span className={labelClass}>Produces</span>
                    <span>{step.produces}</span>
                  </p>
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}

      {paper.decisions && paper.decisions.length > 0 && (
        <section className={sectionClass} aria-labelledby="wp-decisions">
          <h2 id="wp-decisions" className={sideHeadClass}>
            Decisions
          </h2>
          <div className={decisionsClass}>
            {paper.decisions.map((d) => (
              <div key={d.decision} className={decisionClass}>
                <h3 className={decisionTitleClass}>{d.decision}</h3>
                <p className={decisionWhyClass}>{d.why}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {paper.outcome && (
        <section className={sectionClass} aria-labelledby="wp-outcome">
          <h2 id="wp-outcome" className={sideHeadClass}>
            Outcome
          </h2>
          <p className={proseClass}>{paper.outcome}</p>
        </section>
      )}

      {paper.references && paper.references.length > 0 && (
        <section className={sectionClass} aria-labelledby="wp-references">
          <h2 id="wp-references" className={sideHeadClass}>
            References
          </h2>
          <ul className={plainListClass}>
            {paper.references.map((ref) => (
              <li key={ref.url} className={referenceClass}>
                <a href={ref.url} rel="noreferrer" className={linkClass}>
                  {ref.title}
                </a>
                <span className={referenceHostClass}>{hostOf(ref.url)}</span>
                {ref.note && <p className={referenceNoteClass}>{ref.note}</p>}
              </li>
            ))}
          </ul>
        </section>
      )}

      {((paper.stack && paper.stack.length > 0) || paper.liveUrl) && (
        <section className={sectionClass} aria-labelledby="wp-built-with">
          <h2 id="wp-built-with" className={sideHeadClass}>
            Built with
          </h2>
          <div>
            {paper.stack && paper.stack.length > 0 && (
              <ul className={stackClass}>
                {paper.stack.map((item) => (
                  <li key={item} className={stackItemClass}>
                    {item}
                  </li>
                ))}
              </ul>
            )}
            {paper.liveUrl && (
              <p className={liveClass}>
                <a href={paper.liveUrl} rel="noreferrer" className={linkClass}>
                  {hostOf(paper.liveUrl)}
                </a>
              </p>
            )}
          </div>
        </section>
      )}
    </article>
  )
}

// Two columns from `lg`: a 12rem side-head, a 3rem gutter, a 40rem measure.
// Below `lg` the head stacks above the text. The widths are repeated as
// literals rather than shared through a constant so Panda has nothing to
// evaluate.

const articleClass = css({
  bg: 'bg',
  color: 'text',
  fontFamily: 'body',
  fontWeight: 'normal',
  fontSize: '1.125rem',
  lineHeight: '1.65',
  letterSpacing: '0',
  textTransform: 'none',
  textAlign: 'left',
  paddingTop: { base: '2.5rem', lg: '5rem' },
  paddingBottom: { base: '3.5rem', lg: '7rem' },
  paddingLeft: { base: '1.25rem', md: '2.5rem', lg: '4rem' },
  paddingRight: { base: '1.25rem', md: '2.5rem', lg: '4rem' },
  overflowWrap: 'break-word',
})

// The opening block sits in the text column, so it lines up with every
// section's prose.
const columnClass = css({
  maxWidth: { base: '40rem', lg: '55rem' },
  marginLeft: 'auto',
  marginRight: 'auto',
  paddingLeft: { base: '0', lg: '15rem' },
})

const sectionClass = css({
  display: 'grid',
  gridTemplateColumns: { base: 'minmax(0, 1fr)', lg: 'minmax(0, 12rem) minmax(0, 40rem)' },
  columnGap: '3rem',
  rowGap: '1rem',
  justifyContent: 'center',
  maxWidth: { base: '40rem', lg: 'none' },
  marginLeft: 'auto',
  marginRight: 'auto',
  marginTop: { base: '3rem', lg: '4.5rem' },
  paddingTop: { base: '1.25rem', lg: '1.5rem' },
  borderTop: '1px solid',
  borderColor: 'border',
})

const labelClass = css({
  display: 'block',
  fontFamily: 'display',
  fontWeight: 'normal',
  fontSize: '0.75rem',
  lineHeight: '1.4',
  letterSpacing: '0.1em',
  textTransform: 'uppercase',
  color: 'textMuted',
})

const sideHeadClass = css({
  margin: '0',
  fontFamily: 'display',
  fontWeight: 'bold',
  fontSize: '0.875rem',
  lineHeight: '1.4',
  letterSpacing: '0.1em',
  textTransform: 'uppercase',
  color: 'text',
  // Level with the first line of prose beside it.
  paddingTop: { base: '0', lg: '0.35rem' },
})

const factsClass = css({
  display: 'grid',
  gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', md: 'repeat(5, auto)' },
  justifyContent: { md: 'space-between' },
  columnGap: '1.5rem',
  rowGap: '1.25rem',
  margin: '0',
  paddingBottom: '1.5rem',
  borderBottom: '2px solid',
  borderColor: 'borderStrong',
})

const factValueClass = css({
  margin: '0',
  marginTop: '0.25rem',
  fontSize: '1rem',
  lineHeight: '1.4',
  color: 'text',
})

const ledeClass = css({
  margin: '0',
  marginTop: { base: '2rem', lg: '2.5rem' },
  fontSize: { base: '1.3125rem', lg: '1.5rem' },
  lineHeight: '1.5',
  color: 'text',
  textWrap: 'pretty',
})

const proseClass = css({
  margin: '0',
  color: 'text',
  textWrap: 'pretty',
})

const plainListClass = css({
  margin: '0',
  padding: '0',
  listStyle: 'none',
})

const constraintClass = css({
  display: 'grid',
  gridTemplateColumns: '0.5rem minmax(0, 1fr)',
  columnGap: '1rem',
  marginTop: '0.875rem',
  _first: { marginTop: '0' },
})

const bulletClass = css({
  width: '0.5rem',
  height: '0.5rem',
  marginTop: '0.7rem',
  bg: 'accent',
})

const phaseClass = css({
  display: 'grid',
  gridTemplateColumns: '2.75rem minmax(0, 1fr)',
  columnGap: '1rem',
  paddingTop: '1.5rem',
  paddingBottom: '1.5rem',
  borderTop: '1px solid',
  borderColor: 'border',
  _first: { paddingTop: '0', borderTop: 'none' },
  _last: { paddingBottom: '0' },
})

const phaseNumberClass = css({
  fontFamily: 'display',
  fontWeight: 'normal',
  fontSize: '0.875rem',
  lineHeight: '1.9',
  letterSpacing: '0.04em',
  color: 'textMuted',
  fontVariantNumeric: 'tabular-nums',
})

const phaseNameClass = css({
  margin: '0',
  fontFamily: 'display',
  fontWeight: 'bold',
  fontSize: '1.125rem',
  lineHeight: '1.45',
  letterSpacing: '0',
  textTransform: 'none',
  color: 'text',
})

const phaseDoesClass = css({
  margin: '0',
  marginTop: '0.375rem',
  color: 'text',
  textWrap: 'pretty',
})

const producesClass = css({
  display: 'flex',
  flexWrap: 'wrap',
  alignItems: 'baseline',
  columnGap: '0.75rem',
  margin: '0',
  marginTop: '0.625rem',
  fontSize: '1rem',
  lineHeight: '1.5',
  color: 'textMuted',
})

const decisionsClass = css({
  display: 'grid',
  rowGap: '1.25rem',
})

const decisionClass = css({
  bg: 'surface',
  borderLeft: '3px solid',
  borderColor: 'accent',
  paddingTop: { base: '1.25rem', md: '1.75rem' },
  paddingBottom: { base: '1.25rem', md: '1.75rem' },
  paddingLeft: { base: '1.25rem', md: '2rem' },
  paddingRight: { base: '1.25rem', md: '2rem' },
})

const decisionTitleClass = css({
  margin: '0',
  fontFamily: 'display',
  fontWeight: 'bold',
  fontSize: { base: '1.1875rem', md: '1.375rem' },
  lineHeight: '1.3',
  letterSpacing: '0',
  textTransform: 'none',
  color: 'text',
  textWrap: 'balance',
})

const decisionWhyClass = css({
  margin: '0',
  marginTop: '0.75rem',
  color: 'text',
  textWrap: 'pretty',
})

const referenceClass = css({
  paddingTop: '1.25rem',
  paddingBottom: '1.25rem',
  borderTop: '1px solid',
  borderColor: 'border',
  _first: { paddingTop: '0', borderTop: 'none' },
  _last: { paddingBottom: '0' },
})

const linkClass = css({
  color: 'text',
  fontWeight: 'medium',
  textDecoration: 'underline',
  textDecorationColor: 'accent',
  textDecorationThickness: '2px',
  textUnderlineOffset: '0.2em',
  _hover: { textDecorationThickness: '3px' },
  _focusVisible: { outline: '2px solid', outlineColor: 'accent', outlineOffset: '3px' },
})

const referenceHostClass = css({
  display: 'block',
  marginTop: '0.25rem',
  fontFamily: 'display',
  fontSize: '0.75rem',
  lineHeight: '1.4',
  letterSpacing: '0.04em',
  color: 'textMuted',
})

const referenceNoteClass = css({
  margin: '0',
  marginTop: '0.5rem',
  fontSize: '1rem',
  lineHeight: '1.6',
  color: 'textMuted',
  textWrap: 'pretty',
})

const stackClass = css({
  display: 'flex',
  flexWrap: 'wrap',
  columnGap: '0.5rem',
  rowGap: '0.5rem',
  margin: '0',
  padding: '0',
  listStyle: 'none',
})

const stackItemClass = css({
  border: '1px solid',
  borderColor: 'borderStrong',
  paddingTop: '0.25rem',
  paddingBottom: '0.25rem',
  paddingLeft: '0.75rem',
  paddingRight: '0.75rem',
  fontSize: '0.9375rem',
  lineHeight: '1.5',
  color: 'text',
})

const liveClass = css({
  margin: '0',
  marginTop: '1.5rem',
})
