import { css, cx } from '../../styled-system/css'
import { identity } from '../content/about'

/**
 * The brand lockup. Generated by the orchestrator from
 * scripts/templates/BrandLockup.tsx.template on every run, exactly the way
 * app/routes/__root.tsx is. Do not edit by hand and do not draw the mark
 * anywhere else — scripts/utils/build-validator.js fails the build over an
 * `app/assets/logo*.svg` import or a pasted path in any file the engineer owns.
 *
 * Why it exists: the mark was re-implemented from scratch every night and kept
 * shipping wrong. It vanished entirely on 2026-07-10, came back as "a gray box"
 * on 2026-07-22, and rendered at 11px on 2026-08-30 against a mockup that had
 * it at 44px. See issue #254.
 *
 * SIZE. Every dimension in here is relative to the lockup's own font-size,
 * which is a step on the day's chassis ramp — so the lockup scales with the
 * type rather than fighting it. The mark stands MARK_TO_CAP (2.4) cap-heights
 * tall, cap-height taken as 0.7em, giving a flat 1.68em. The step itself is
 * bounded so that 1.68em lands inside the Brand Contract's band for the
 * variant, which means no ramp ratio can push the mark outside the size the
 * Art Director declared, and the wordmark shrinks with it rather than being
 * left oversized beside a cut-down mark. The variant→step map and the bands
 * live in scripts/utils/brand-lockup.js, which is what the prompts and the
 * validator read.
 *
 * ALIGNMENT. Horizontal variants align the mark to the wordmark's cap-height,
 * not to its line box. With line-height 1 the text box top sits about 0.1em
 * above the cap line and the cap band is 0.7em deep, so the cap band's centre
 * is 0.45em below the text box top. The mark's centre is 0.84em below the row
 * top, so the text column is padded down by 0.39em to bring the two together.
 * Positive, so nothing overflows the row upward.
 */

type BrandLockupVariant =
  | 'mark-only-sm'
  | 'mark-only-md'
  | 'horizontal-sm'
  | 'horizontal-md'
  | 'stacked-md'
  | 'stacked-lg'

type BrandLockupMode = 'original' | 'single-color'

/**
 * Colour tokens the lockup will accept for single-color mode.
 *
 * Deliberately only three. Semantic token sets are re-authored nightly and
 * are not guaranteed across presets — `textMuted` is missing from roughly one
 * preset in five — and PandaCSS resolves style values at extract time, so a
 * runtime token name produces a class with no rule behind it. `text`, `bg` and
 * `accent` are the same three app/routes/__root.tsx.template restricts itself
 * to, for the same reason. Omit the prop and the mark inherits `currentColor`
 * from wherever it is placed, which is the more idiomatic route: wrap the
 * lockup in an element whose `color` you set, or pass a `className`.
 */
type BrandLockupColor = 'text' | 'bg' | 'accent'

type BrandLockupProps = {
  variant?: BrandLockupVariant
  mode?: BrandLockupMode
  color?: BrandLockupColor
  /** Render identity.role beneath the wordmark. Declared per day in ===HEADER===. */
  roleLine?: boolean
  className?: string
}

/**
 * One static rule per variant: the ramp step the lockup is set at, bounded so
 * the mark it drives lands inside the Brand Contract's band for that variant.
 *
 * The bound is on the FONT SIZE rather than on the mark, so the two never come
 * apart. The mark is a flat 1.68em, which is 2.4 cap-heights, always. Clamping
 * the mark instead would leave the wordmark at full ramp size beside a mark
 * that had been cut down to fit — on a 1.5-ratio chassis that put an 81px
 * "Doug March" next to a 96px mark and the wordmark won. Squeezing the step
 * instead keeps the pair in proportion at every ratio in the catalog. The
 * bounds are the band divided by 1.68; the table lives in
 * scripts/utils/brand-lockup.js.
 */
const variantStyles: Record<BrandLockupVariant, string> = {
  'mark-only-sm': css({ fontSize: 'clamp(14.286px, token(fontSizes.base), 19.048px)' }),
  'mark-only-md': css({ fontSize: 'clamp(23.81px, token(fontSizes.lg), 33.333px)' }),
  'horizontal-sm': css({ fontSize: 'clamp(11.905px, token(fontSizes.base), 16.667px)' }),
  'horizontal-md': css({ fontSize: 'clamp(19.048px, token(fontSizes.lg), 28.571px)' }),
  'stacked-md': css({ fontSize: 'clamp(23.81px, token(fontSizes.lg), 33.333px)' }),
  'stacked-lg': css({ fontSize: 'clamp(38.095px, token(fontSizes.2xl), 57.143px)' }),
}

const colorStyles: Record<BrandLockupColor, string> = {
  text: css({ color: 'text' }),
  bg: css({ color: 'bg' }),
  accent: css({ color: 'accent' }),
}

const rootRow = css({
  display: 'inline-flex',
  flexDirection: 'row',
  alignItems: 'flex-start',
  gap: '0.42em',
})

const rootColumn = css({
  display: 'inline-flex',
  flexDirection: 'column',
  alignItems: 'center',
  gap: '0.34em',
})

const rootMark = css({ display: 'inline-flex' })

/** 1.68em is 2.4 cap-heights, taking cap-height as 0.7em. The viewBox is
 * 71x59, so the width follows from the height rather than being asserted. */
const markStyle = css({
  height: '1.68em',
  width: 'calc(1.68em * 71 / 59)',
  display: 'block',
  flexShrink: 0,
})

/** Cap-height alignment for the horizontal variants: half the mark (0.84em)
 * minus the 0.45em from text-box top to cap-band centre. See the note above. */
const textColumnRow = css({
  display: 'flex',
  flexDirection: 'column',
  paddingTop: '0.39em',
})

const textColumnStacked = css({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
})

const wordmark = css({
  fontFamily: 'display',
  fontWeight: 700,
  lineHeight: 1,
  letterSpacing: '-0.015em',
  whiteSpace: 'nowrap',
})

/**
 * The role line is set off the ramp on purpose. At `horizontal-sm` the lockup
 * runs at the `base` step, and a proportional role line would land near 7px —
 * under the Art Director's own 14px floor. The clamp keeps it legible at the
 * small end and stops it competing with the wordmark at the large end.
 */
const roleLineStyle = css({
  fontFamily: 'body',
  fontSize: 'clamp(13px, 0.42em, 16px)',
  lineHeight: 1.2,
  letterSpacing: '0.09em',
  textTransform: 'uppercase',
  opacity: 0.72,
  marginTop: '0.42em',
  whiteSpace: 'nowrap',
})

/**
 * The mark itself, inlined here and nowhere else in the app. `original` adds
 * the white disc the mark is drawn on and keeps the authored greens and blue;
 * `single-color` drops the disc and inherits one colour through currentColor.
 * Geometry is identical either way — the Brand Contract forbids redrawing it.
 */
function Mark({ mode, labelled }: { mode: BrandLockupMode; labelled: boolean }) {
  const original = mode === 'original'
  const ink = original ? '#7AC042' : 'currentColor'
  const hairline = original ? '#DADADA' : 'currentColor'
  const tail = original ? '#008ED3' : 'currentColor'
  const dot = original ? '#BBBDBF' : 'currentColor'
  return (
    <svg
      viewBox="0 0 71 59"
      className={markStyle}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      focusable="false"
      {...(labelled
        ? { role: 'img', 'aria-label': `${identity.name} logo` }
        : { 'aria-hidden': true })}
    >
      {original ? (
        <path
          d="M29.8924 0.440186C13.8749 0.440186 0.889618 13.4254 0.889618 29.443C0.889618 45.4613 13.8749 58.4466 29.8924 58.4466C45.9108 58.4466 58.896 45.4613 58.896 29.443C58.8952 13.4254 45.91 0.440186 29.8924 0.440186Z"
          fill="white"
        />
      ) : null}
      <path
        d="M29.8925 0.440186C45.91 0.440257 58.8956 13.4256 58.8965 29.4431C58.8964 45.4614 45.9108 58.4469 29.8925 58.447C13.8751 58.447 0.889689 45.4614 0.889618 29.4431C0.889618 13.4256 13.875 0.440186 29.8925 0.440186ZM29.8935 5.97729C16.9329 5.97729 6.42673 16.4841 6.42673 29.4431C6.4268 42.4021 16.9329 52.9099 29.8935 52.9099C42.8532 52.9098 53.3583 42.402 53.3584 29.4431C53.3584 16.4842 42.854 5.97745 29.8935 5.97729Z"
        fill={ink}
      />
      <circle cx="30.0829" cy="29.3002" r="0.98668" fill={dot} />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M47.8611 29.3418C47.8611 39.1396 39.9198 47.0816 30.1214 47.0816C20.3244 47.0816 12.3823 39.1396 12.3823 29.3418C12.3823 19.5463 20.3244 11.6013 30.1214 11.6013C39.9198 11.6013 47.8611 19.5463 47.8611 29.3418Z"
        stroke={hairline}
        strokeWidth="0.25"
      />
      <circle cx="30.1217" cy="29.3415" r="18.8911" stroke={hairline} strokeWidth="0.25" />
      <circle cx="30.1217" cy="29.3416" r="20.033" stroke={hairline} strokeWidth="0.25" />
      <circle cx="30.1217" cy="29.3415" r="21.1098" stroke={hairline} strokeWidth="0.25" />
      <circle cx="30.1217" cy="29.3416" r="22.114" stroke={hairline} strokeWidth="0.25" />
      <path
        d="M68.9722 9.76277C68.1324 8.9222 66.8896 8.48386 65.2438 8.44856C65.2922 6.88646 64.8416 5.63053 63.8902 4.67997C62.9667 3.7565 61.8454 3.30913 60.523 3.33293C59.2022 3.35838 58.0612 3.85254 57.0967 4.81706L52.8331 9.08227L52.8134 9.06175L31.8666 30.0094C30.7215 31.1553 29.7373 31.317 28.914 30.4937C28.5708 30.1506 28.396 29.7385 28.387 29.2542C28.3787 28.7707 28.5413 28.3627 28.8721 28.0311C29.2169 27.6872 29.6281 27.5148 30.1108 27.5074C30.5918 27.5025 30.9989 27.665 31.333 27.9999C31.5957 28.2626 31.7599 28.6287 31.8239 29.0917L35.3553 25.5611C34.999 25.1499 34.7265 24.8494 34.5377 24.6631C33.3491 23.4737 31.8789 22.8835 30.1313 22.895C28.382 22.9056 26.9053 23.5139 25.7011 24.7181C24.4575 25.9625 23.8426 27.4508 23.8607 29.182C23.8788 30.9148 24.5248 32.4154 25.7988 33.6893C26.4399 34.3296 27.2024 34.8156 28.0923 35.1431C28.9821 35.4706 29.8604 35.5954 30.7297 35.5149C32.2385 35.3762 33.6487 34.653 34.958 33.3429L56.0247 12.2763L56.0091 12.2598L59.5298 8.73833C59.8647 8.40424 60.1569 8.21133 60.4138 8.14731C60.6987 8.03485 60.9425 8.07343 61.1403 8.27126C61.3332 8.46334 61.3997 8.66773 61.3389 8.8828C61.2774 9.09787 61.0705 9.38353 60.7143 9.7406L55.7398 14.7142C56.5213 16.0998 57.1944 17.552 57.7444 19.0664L63.8007 13.0101C64.1348 12.6752 64.4287 12.4807 64.6856 12.4199C64.9704 12.3074 65.2134 12.3444 65.4104 12.5414C65.6017 12.7302 65.6649 12.9338 65.5984 13.1423C65.5336 13.3541 65.3251 13.6381 64.9688 13.9943L58.2763 20.6868C58.7902 22.418 59.1513 24.2149 59.3336 26.0676L68.4796 16.9207C69.6436 15.7584 70.2757 14.6165 70.3734 13.501C70.5088 12.0768 70.0409 10.8307 68.9722 9.76277Z"
        fill={tail}
      />
    </svg>
  )
}

export function BrandLockup({
  variant = 'horizontal-md',
  mode = 'single-color',
  color,
  roleLine = false,
  className,
}: BrandLockupProps) {
  const sizing = variantStyles[variant] ?? variantStyles['horizontal-md']
  const tint = color ? colorStyles[color] : undefined

  if (variant === 'mark-only-sm' || variant === 'mark-only-md') {
    return (
      <span className={cx(rootMark, sizing, tint, className)}>
        <Mark mode={mode} labelled />
      </span>
    )
  }

  const stacked = variant === 'stacked-md' || variant === 'stacked-lg'

  return (
    <span className={cx(stacked ? rootColumn : rootRow, sizing, tint, className)}>
      <Mark mode={mode} labelled={false} />
      <span className={stacked ? textColumnStacked : textColumnRow}>
        <span className={wordmark}>{identity.name}</span>
        {roleLine ? <span className={roleLineStyle}>{identity.role}</span> : null}
      </span>
    </span>
  )
}
