import { css, cx } from '../../styled-system/css'
import { calloutLineFor, siteCallout } from '../content/callout'

/**
 * The home page callout. Generated by the orchestrator from
 * scripts/templates/SiteCallout.tsx.template on every run, the way
 * app/components/BrandLockup.tsx is. Do not edit by hand.
 *
 * It is the one place the site says what it is doing, which is the subject
 * every agent is banned from (SELF_REFERENCE in scripts/utils/copy-tells.js).
 * So no agent writes it. The copy is hand-written in app/content/callout.ts,
 * the engineer places <SiteCallout /> on the home page below the hero and
 * above the footer, and scripts/utils/build-validator.js fails the build when
 * app/routes/index.tsx does not render it. See #532.
 *
 * It also carries home's archive link. __root.tsx skips its own link on `/`
 * so the page says the idea once, which is why that validator check matters:
 * without the callout, home has no way into the archive (#155).
 *
 * TOKENS. Colours are from the frozen semantic set
 * (scripts/utils/semantic-contract.js), fonts, sizes and spacing from the
 * chassis preset. Every night defines all of them, so the callout wears the
 * day's palette and type without naming anything a preset can drop. Structure
 * and proportions are fixed here and take no props.
 *
 * The archive link's ink is the one colour chosen per night rather than fixed
 * (#566): the quietest of `textFaint`, `textMuted` and `text` that reaches
 * 4.5:1 on `bgAlt`, written in below by the orchestrator
 * (scripts/utils/archive-link-ink.js).
 *
 * DATE. The run's date and the archive count are written in below by the
 * orchestrator. The line is picked from the date, never from the visitor's
 * clock, so an archived page shows the line it shipped with.
 */

const DESIGN_DATE = '2026-09-26'
const ARCHIVE_COUNT = 146

const root = css({
  display: 'block',
  bg: 'bgAlt',
  color: 'text',
  borderTop: '1px solid',
  borderColor: 'borderStrong',
  paddingTop: { base: '5', md: '6' },
  paddingBottom: { base: '5', md: '6' },
  paddingLeft: { base: '3', md: '6' },
  paddingRight: { base: '3', md: '6' },
})

const inner = css({
  display: 'grid',
  gridTemplateColumns: { base: '1fr', lg: 'minmax(0, 38rem) auto' },
  justifyContent: 'space-between',
  alignItems: 'end',
  rowGap: '4',
  columnGap: '6',
  maxWidth: '80rem',
  marginLeft: 'auto',
  marginRight: 'auto',
})

const line = css({
  margin: '0',
  fontFamily: 'body',
  fontSize: { base: 'base', md: 'md' },
  fontWeight: 'normal',
  // `snug` is the headline leading, 1.1, and at `md` this line runs to three
  // lines of 24px copy (#564).
  lineHeight: 'normal',
  letterSpacing: 'normal',
  textWrap: 'pretty',
})

const links = css({
  display: 'flex',
  flexWrap: 'wrap',
  alignItems: 'center',
  columnGap: '5',
  rowGap: '1',
  fontFamily: 'display',
  fontSize: 'sm',
  letterSpacing: 'wide',
})

const link = css({
  display: 'inline-flex',
  alignItems: 'center',
  minHeight: '44px',
  textDecoration: 'underline',
  textDecorationThickness: '2px',
  textUnderlineOffset: '0.3em',
  whiteSpace: 'nowrap',
  transition: 'text-decoration-color 0.2s ease, color 0.2s ease',
  _focusVisible: { outline: '2px solid', outlineColor: 'accent', outlineOffset: '4px' },
})

const primary = css({
  color: 'text',
  fontWeight: 'bold',
  textDecorationColor: 'accent',
  _hover: { textDecorationColor: 'text' },
})

const secondary = css({
  color: 'textFaint',
  textDecorationColor: 'borderStrong',
  _hover: { color: 'text', textDecorationColor: 'accent' },
})

export function SiteCallout() {
  return (
    <aside aria-label={siteCallout.label} className={root} data-site-callout>
      <div className={inner}>
        <p className={line}>{calloutLineFor(DESIGN_DATE)}</p>
        <div className={links}>
          <a
            href={siteCallout.whitePaper.href}
            className={cx(link, primary)}
            data-callout-white-paper
          >
            {siteCallout.whitePaper.label}
          </a>
          <a href={siteCallout.archive.href} className={cx(link, secondary)} data-archive-link>
            {siteCallout.archive.label} · {ARCHIVE_COUNT} designs
          </a>
        </div>
      </div>
    </aside>
  )
}
